apiVersion: v2
name: fireworks
description: Krateo PlatformOps fireworks
type: application
icon: "https://github.com/krateoplatformops/community/blob/main/logos/black/icon.svg"

version: 0.1.0
appVersion: 0.1.0

maintainers:
  - name: Mauro Sala
    email: mauro.sala@kiratech.it
    url: https://krateo.io
  - name: Luca Sepe
    email: luca.sepe@kiratech.it
    url: https://www.kiratech.it
