---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: krateo.io
    component: {{ .Values.name }}
spec:
  selector:
    app: krateo.io
    component: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
